### ISSUE TITLE
Issue While Installing

### ISSUE THREAD

**Issue by pradhumna22** [reliefs/gitbot#1]
Traceback (most recent call last):
  File "D:\gitbot2.0\gitbot\run.py", line 1, in <module>
    from gitbot import Bot
  File "D:\gitbot2.0\gitbot\gitbot\__init__.py", line 1, in <module>
    from . import Bot
  File "D:\gitbot2.0\gitbot\gitbot\Bot.py", line 1, in <module>
    from github3 import login, GitHub
ModuleNotFoundError: No module named 'github3' IS THE EROR COMMING

**Comment by steffanjensen** [comment]
> github3

Write in cmd/bash:
pip install github3.py

More info:
https://pypi.org/project/github3.py/
